### ISSUE TITLE
Page set to active yet returns an error

### ISSUE THREAD

**Issue by Baker** [startupengine/startupengine#12]
Any page I set `active` returns errors see below: 

http://francispbaker-blog.herokuapp.com/
http://francispbaker-blog.herokuapp.com/help
http://francispbaker-blog.herokuapp.com/articles 
etc

Proof they are set to active: 
![image](https://user-images.githubusercontent.com/9560564/36287957-4497d2d8-1286-11e8-9786-f1cb5d9f7870.png)

**Comment by luckyrabbitllc** [comment]
Okay, so the error is

> View [theme.templates.global.menu] not found. (View: /app/resources/views/layouts/page.blade.php) 

I'm assuming that you're using a fork of the default theme, and that you're on heroku -- is that correct?

If so, this might have happened if you ran SyncGit without re-deploying (restarting the server) afterwards. Try that. 

The file definitely exists within the theme (https://github.com/luckyrabbitllc/Startup-Engine-Template/blob/master/resources/views/theme/templates/global/menu.blade.php) so it's just a matter of making sure the file extracts properly.

**Comment by Baker** [comment]
@luckyrabbitllc are we supposed to install a theme? Thought that was included in the one click install, I didn't see that mentioned that it wasn't. Lmk and please provide instructions on how to install it if possible

**Comment by luckyrabbitllc** [comment]
Yes, it is installed by default, that's where the articles, landing, etc pages came from. The error is saying that some particular files are missing, but they should be there. It's possible that the extraction of the package failed. If that's the issue, try re-deploying.

**Comment by Baker** [comment]
Hey there -

I have tried to reinstall multiple times with Heroku and this happens every time.

**Comment by Baker** [comment]
Updating on this: I have redeployed twice, same issue.
