### ISSUE TITLE
Undefined variable: values

### ISSUE THREAD

**Issue by eleazarbr** [startupengine/startupengine#14]
I get the following error when trying to login: 

**Undefined variable: values (View: /app/resources/views/app/dashboard/index.blade.php)**

I even get an error when I run `php artisan command:SyncGit reset`

account schema exists. 
articles schema exists. 
features schema exists. 
In SyncGit.php line 192: 
Trying to get property 'slug' of non-object 

I followed all the steps to deploy, I even read the other closed issues however I didn't find anything concerning this problem.

Regards.

**Comment by synectiks-code** [comment]
i also get the same issue, would really appreciate if somebody can help

**Comment by synectiks-code** [comment]
I found the reason , in feature page.json is malformed.

**Comment by eleazarbr** [comment]
I think I'll also check it locally, it's an interesting project... hope to bring some solution

**Comment by wmfleming** [comment]
Anyone figure out a fix for this?
