### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by sleepycodernotes** [startupengine/startupengine#15]
mysql compatible?

**Comment by startupengine** [comment]
Technically yes but not officially supported, for performance reasons and because of issues with JSON columns

**Comment by startupengine** [comment]
It ships with a full containerized development environment, so you shouldn't need to supply your own DB during development, and when deploying to Heroku, it automatically provisions a PGSQL database - check out the readme.

**Comment by sleepycodernotes** [comment]
I see. Thanks for help.

**Comment by sleepycodernotes** [comment]
Can someone help me migrate to Mysql?
