### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by mysykez** [startupengine/startupengine#16]
hello this is good app . but so hard to install this app
im using linux valet & mysql for database & nginx
composer install success but im migrate from folder database to phpmyadmin im get error

> Migrating: 2017_11_18_003108_create_post_types_table
> 
> In Connection.php line 664:
> 
>   SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'slug' used in key specification with
>   out a key length (SQL: alter table `post_types` add unique `post_types_slug_unique`(`slug`))
> 
> 
> In Connection.php line 458:
> 
>   SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'slug' used in key specification with out a key length

im search in google its error unique slug

and i try with heroku but same error again

> !     Push rejected, failed to compile PHP app.
>  !     Push failed

I've been wanting to try your application for 2018 but it's the same mistake for me :(
sorry bad english

**Comment by startupengine** [comment]
Are you using a PostgreSQL database?

**Comment by mysykez** [comment]
> 
> 
> Are you using a PostgreSQL database?

oke im back to windows and use laragon to try your app . nginx-posgresSql-php7
its works . thanks . and your app good
But I am not familiar with PGSQL.
and i cant login to your app . admin@example.com and password after migrate

**Comment by startupengine** [comment]
Make sure you run the initial migrate with the seeder. Here are all the setup scripts from composer.json

```@php artisan key:generate
php artisan migrate:fresh --seed
php artisan passport:install
php artisan passport:keys```

**Comment by m2ura** [comment]
I use mysql and I get the same error as the guy above even though I ran these commands php artisan key:generate
php artisan migrate:fresh --seed
php artisan passport:install
php artisan passport:keys

I end up with In Connection.php line 664:
                                                                
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB  
  /TEXT column 'slug' used in key specification without a key   
  length (SQL: alter table `post_types` add unique `post_types  
  _slug_unique`(`slug`))                                        
                                                                

In Connection.php line 458:
                                                                
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB  
  /TEXT column 'slug' used in key specification without a key   
  length

**Comment by m2ura** [comment]
fixed it by changing $table->text('slug')->unique(); to $table->string('slug', 255)->unique();
As well as others that cause the same problem when migrating.
